#%RAML 1.0
title: "Vendors"
baseUri: https://github.com/folio-org/mod-vendors
version: v1

documentation:
  - title: Addresses
    content: <b>CRUD APIs used to manage addresses.</b>

types:
    address: !include acq-models/mod-vendors/schemas/address.json
    address_collection: !include acq-models/mod-vendors/schemas/address_collection.json
    UUID:
      type: string
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
    orderable: !include raml-util/traits/orderable.raml
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml


/vendor-storage/addresses:
  type:
    collection:
      exampleCollection: !include acq-models/mod-vendors/examples/address_collection.sample
      exampleItem: !include acq-models/mod-vendors/examples/address_post.sample
      schemaCollection: address_collection
      schemaItem: address
  get:
    description: Get list of addresses
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a Address
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-vendors/examples/address_get.sample
        schema: address
