#%RAML 1.0
title: "Vendors"
baseUri: https://github.com/folio-org/mod-vendors
version: v1

documentation:
  - title: Aliases
    content: <b>CRUD APIs used to manage alerts.</b>

types:
    alias: !include acq-models/mod-vendors/schemas/alias.json
    alias_collection: !include acq-models/mod-vendors/schemas/alias_collection.json
    UUID:
      type: string
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
    orderable: !include raml-util/traits/orderable.raml
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml


/vendors/aliases:
  type:
    collection:
      exampleCollection: !include acq-models/mod-vendors/examples/alias_collection.sample
      exampleItem: !include acq-models/mod-vendors/examples/alias_post.sample
      schemaCollection: alias_collection
      schemaItem: alias
  get:
    description: Get list of aliases
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a Alias
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-vendors/examples/alias_get.sample
        schema: alias
