#%RAML 1.0
title: "Vendors"
baseUri: https://github.com/folio-org/mod-vendors
version: v1

documentation:
  - title: Contact Persons
    content: <b>CRUD APIs used to manage contact persons.</b>

types:
    contact_person: !include acq-models/mod-vendors/schemas/contact_person.json
    contact_person_collection: !include acq-models/mod-vendors/schemas/contact_person_collection.json
    UUID:
      type: string
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
    orderable: !include raml-util/traits/orderable.raml
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml


/vendors/contact_persons:
  type:
    collection:
      exampleCollection: !include acq-models/mod-vendors/examples/contact_person_collection.sample
      exampleItem: !include acq-models/mod-vendors/examples/contact_person_post.sample
      schemaCollection: contact_person_collection
      schemaItem: contact_person
  get:
    description: Get list of contact persons
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a Contact Person
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-vendors/examples/contact_person_get.sample
        schema: contact_person
