#%RAML 0.8
title: "mod-vendors"
baseUri: https://github.com/folio-org/mod-vendors
version: v1

documentation:
  - title: mod-vendors
    content: <b>This module implements the CRUD interface.</b>

schemas:
  - interface.json: !include acq-models/mod-vendors/schemas/interface.json
  - interface_collection: !include acq-models/mod-vendors/schemas/interface_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml


/interface:
  type:
    collection:
      exampleCollection: !include acq-models/mod-vendors/examples/interface_collection.sample
      exampleItem: !include acq-models/mod-vendors/examples/interface_post.sample
      schemaCollection: interface_collection
      schemaItem: interface.json
  get:
    description: Get list of interfaces
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include acq-models/mod-vendors/examples/interface_get.sample
        schema: interface.json
