#%RAML 1.0
title: "Vendors"
baseUri: https://github.com/folio-org/mod-vendors
version: v2.0

documentation:
  - title: Interfaces
    content: <b>CRUD APIs used to manage interfaces.</b>

types:
    interface: !include acq-models/mod-vendors/schemas/interface.json
    interface_collection: !include acq-models/mod-vendors/schemas/interface_collection.json
    UUID:
      type: string
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
    orderable: !include raml-util/traits/orderable.raml
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml


/vendor-storage/interfaces:
  type:
    collection:
      exampleCollection: !include acq-models/mod-vendors/examples/interface_collection.sample
      exampleItem: !include acq-models/mod-vendors/examples/interface_post.sample
      schemaCollection: interface_collection
      schemaItem: interface
  get:
    description: Get list of interfaces
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a Interface
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-vendors/examples/interface_get.sample
        schema: interface
