#%RAML 1.0
title: "Vendors"
baseUri: https://github.com/folio-org/mod-vendors
version: v1

documentation:
  - title: Vendor Types
    content: <b>CRUD APIs used to manage vendor types.</b>

types:
    vendor_type: !include acq-models/mod-vendors/schemas/vendor_type.json
    vendor_type_collection: !include acq-models/mod-vendors/schemas/vendor_type_collection.json
    UUID:
      type: string
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
    orderable: !include raml-util/traits/orderable.raml
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml

/vendors/vendor_types:
  type:
    collection:
      exampleCollection: !include acq-models/mod-vendors/examples/vendor_type_collection.sample
      exampleItem: !include acq-models/mod-vendors/examples/vendor_type_post.sample
      schemaCollection: vendor_type_collection
      schemaItem: vendor_type
  get:
    description: Get list of vendor types
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of Adjustment
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-vendors/examples/vendor_type_get.sample
        schema: vendor_type
