#%RAML 0.8
title: "mod-vendors"
baseUri: https://github.com/folio-org/mod-vendors
version: v1

documentation:
  - title: mod-vendors
    content: <b>This module implements the CRUD interface.</b>

schemas:
  - vendor_url.json: !include acq-models/mod-vendors/schemas/vendor_url.json
  - vendor_url_collection: !include acq-models/mod-vendors/schemas/vendor_url_collection.json
  - url.json: !include acq-models/mod-vendors/schemas/url.json
  - url_collection: !include acq-models/mod-vendors/schemas/url_collection.json
  - category.json: !include acq-models/mod-vendors/schemas/category.json
  - category_collection: !include acq-models/mod-vendors/schemas/category_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml


/vendor_url:
  type:
    collection:
      exampleCollection: !include acq-models/mod-vendors/examples/vendor_url_collection.sample
      exampleItem: !include acq-models/mod-vendors/examples/vendor_url_post.sample
      schemaCollection: vendor_url_collection
      schemaItem: vendor_url.json
  get:
    description: Get list of EDIs
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include acq-models/mod-vendors/examples/vendor_url_get.sample
        schema: vendor_url.json
