#%RAML 0.8
title: "Vendor-Module"
baseUri: http://github.com/org/folio/lsp-apis
version: v1

documentation:
  - title: Vendors Module
    content: <b>This documents the CRUD API calls for vendors</b>

schemas:
  - error: !include schemas/error.json
  - vendor: !include schemas/vendor.json
  - vendorCollection: !include schemas/vendorCollection.json


/vendor:
  put:
    description: Create a new vendor
    body:
      application/json:
        example: !include examples/vendor_create.sample
        schema: vendor
    responses:
      200:
        description: Create-vendor success
        body:
          application/json:
            schema: vendor
      400:
        body:
          application/json:
            schema: error
      403:
        body:
          application/json:
            schema: error
  get:
    description: Get list of vendors
    responses:
      200:
        description: Return a list of the vendors
        body:
          application/json:
            schema: vendorCollection
      400:
        body:
          application/json:
            schema: error
      403:
        body:
          application/json:
            schema: error
  /{vendor_id}:
    get:
      description: Fetch vendor with ID
      responses:
        200:
          description: JSON payload of vendor with ID
          body:
            application/json:
              schema: vendor
        400:
          body:
            application/json:
              schema: error
        403:
          body:
            application/json:
              schema: error
        404:
          body:
            application/json:
              schema: error
    post:
      description: Update vendor with ID
      body:
        application/json:
          schema: vendor
      responses:
        204:
        400:
          body:
            application/json:
              schema: error
        403:
          body:
            application/json:
              schema: error
        404:
          body:
            application/json:
              schema: error
    delete:
      description: Delete vendor with ID
      responses:
        204:
        400:
          body:
            application/json:
              schema: error
        403:
          body:
            application/json:
              schema: error
        404:
          body:
            application/json:
              schema: error