#%RAML 0.8
title: "mod-vendors"
baseUri: https://github.com/folio-org/mod-vendors
version: v1

documentation:
  - title: mod-vendors (category)
    content: <b>This module implements the Vendor-CRUD interface.</b>

schemas:
  - category.json: !include schemas/category.json
  - categoryCollection: !include schemas/categoryCollection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml


/vendor_category:
  type:
    collection:
      exampleCollection: !include examples/category_collection.sample
      exampleItem: !include examples/category_post.sample
      schemaCollection: categoryCollection
      schemaItem: category.json
  get:
    description: Get list of categories
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include examples/category_get.sample
        schema: category.json
